# Uncomment if you are using Rails' asset pipeline
    # load 'deploy/assets'
Dir['vendor/plugins/*/recipes/*.rb', 'config/deploy/*/*.rb'].each { |plugin| load(plugin) }
load 'config/deploy' # remove this line to skip loading any of the default tasks
