CREATE ROLE manatee_user LOGIN ENCRYPTED PASSWORD 'md5396d3fb406e42a8f4b91c4c1a2457782' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE DATABASE manatees_wildtrack WITH OWNER = manatee_user ENCODING = 'UTF8' TABLESPACE = pg_default;
ALTER DATABASE manatees_wildtrack OWNER TO manatee_user;